## This configuration replicates the example given in
##  https://www.ddbj.nig.ac.jp/ddbj/file-format-e.html#annotation
##

[COMMON]
[COMMON.SUBMITTER]
ab_name = [
    "Robertson,G.R.",
    "Mishima,H."
]
contact = "Hanako Mishima"
email = "mishima@ddbj.nig.ac.jp"
phone = "81-55-981-6853"
fax = "81-55-981-6853"
phext =	"3207"
institute = "National Institute of Genetics"
department = "DNA Data Bank of Japan"
country = "Japan"
state = "Shizuoka"
city = "Mishima"
street = "Yata 1111"
zip = "411-8540"

[COMMON.REFERENCE]
title = "Mouse Genome Sequencing"
ab_name = [
    "Robertson,G.R.",
    "Mishima,H."
]
year = "2021"
status = "Unpublished"

[COMMON.COMMENT]
line = [
    "Please visit our website URL",
    "http://www.ddbj.nig.ac.jp/"
]

[source]
organism = "Mus musculus"
mol_type = "genomic DNA"
clone = "PC0110"
chromosome = 8
