## -----------------------------------------------------------------------
##        COMMON entry
[COMMON]
[COMMON.DATATYPE]
type = "WGS"

[COMMON.KEYWORD]
# Choose from following: https://www.insdc.org/documents/methodological-keywords
keyword = [
    "WGS",
    "STANDARD_DRAFT"
]

[COMMON.DBLINK]
project = "PRJDB12345"
biosample = "SAMD90000001"
"sequence read archive" = "DRR990000"

[COMMON.SUBMITTER]
contact = "Hanako Mishima"
consrtm = "Zimmermannella faecalis genome sequencing consortium"
ab_name = [
    "Robertson,G.R.",
    "Mishima,H."
]
email = "mishima@ddbj.nig.ac.jp"
phone = "81-55-981-6853"
institute = "National Institute of Genetics"
country = "Japan"
city = "Mishima"
street = "Yata 1111"
zip = "411-8540"

[COMMON.REFERENCE]
title = "Mouse Genome Sequencing"
ab_name = [
    "Robertson,G.R.",
    "Mishima,H."
]
year = "2021"
status = "Unpublished"

# [COMMON.TOPOLOGY]
# circular = ""

[COMMON.COMMENT]
line = ["Please visit our website URL", "http://www.ddbj.nig.ac.jp/"]

[COMMON.ST_COMMENT]
tagset_id = "Genome-Assembly-Data"
"Assembly Method" = "Velvet v.2.0"
"Assembly Name" = "Sfl_assembly01"
"Genome Coverage" = "60x"
"Sequencing Technology" = "454 GS FLX; ABI 3730"

## "source" feature under COMMON has its own macro processing
##   https://www.ddbj.nig.ac.jp/ddbj/file-format-e.html#common
[COMMON.source]
submitter_seqid = "@@[entry]@@"
ff_definition =	"@@[organism]@@ DNA, @@[submitter_seqid]@@"
organism = "Drosophila melanogaster"
mol_type = "genomic DNA"
##
## -----------------------------------------------------------------------


[source]
## -----------------------------------------------------------------------
##        "source" feature
##
##  DDBJ-recommended qualifiers:
##    https://www.ddbj.nig.ac.jp/assets/files/pdf/ddbj/fq-e.pdf
##
## [WARNING] qualifiers for "source" are IGNORED IF [COMMON.source] is defined in this file.
organism = "Drosophila melanogaster"
mol_type = "genomic DNA"

##
## -----------------------------------------------------------------------


[assembly_gap]
## -----------------------------------------------------------------------
##        "assembly_gap" feature
estimated_length = "unknown"     # counts N's if the value is "<COMPUTE>"
gap_type = "within scaffold"
linkage_evidence = "paired-ends" # mandatory if gap_type is "within scaffold" or "repeat within scaffold"
##
## -----------------------------------------------------------------------
