## -----------------------------------------------------------------------
##        COMMON entry
[SUBMITTER]
ab_name = ["Robertson,G.R.", "Mishima,H."]
contact = "Hanako Mishima"
email = "mishima@ddbj.nig.ac.jp"
phone = "81-55-981-6853"
institute = "National Institute of Genetics"
country = "Japan"
city = "Mishima"
street = "Yata 1111"
zip = "411-8540"

[REFERENCE]
title = "Mouse Genome Sequencing"
ab_name = ["Robertson,G.R.", "Mishima,H."]
year = 2017
status = "Unpublished"

[COMMENT]
line = ["Please visit our website URL", "http://www.ddbj.nig.ac.jp/"]
##
## -----------------------------------------------------------------------


[source]
## -----------------------------------------------------------------------
##        "source" feature
##
##  DDBJ-recommended qualifiers:
##    https://www.ddbj.nig.ac.jp/assets/files/pdf/ddbj/fq-e.pdf
##
mol_type = "genomic DNA"
organism = "Drosophila melanogaster"
##
## -----------------------------------------------------------------------


[assembly_gap]
## -----------------------------------------------------------------------
##        "assembly_gap" feature
estimated_length = "unknown"      # counts N's if the value is "<COMPUTE>"
gap_type = "within scaffold"
linkage_evidence = "paired-ends"  # mandatory if gap_type is "within scaffold" or "repeat within scaffold"
##
## -----------------------------------------------------------------------
