# -------------------------------------------
# Found in GFF3 columns
# GFF.parse() used in this tool stores the 2nd, the 6th, and the 8th column
# as qualifiers with name 'source', 'score', and 'phase', respectively.
[source]
target = "note"
prefix = 'source:'

[score]
target = "score"

[phase]
target = "codon_start"  # 0-based in GFF3. Will be transformed to 1-based.

# --------------------------------------------
# Found in GFF3 attributes
[ID]
target = "note"
prefix = "ID:"

[Note]
target = "note"

[Dbxref]
target = "db_xref"

[gene_name]
target = "gene"

[geneID]
target = "gene"

[description]
target = "product"

[eC_number]
target = "EC_number"

[ec_number]
target = "EC_number"

[locus_tag]
target = "locus_tag"
prefix = "<dummy>"

[_Description]
target = "product"
