## --------------------------------------------------------------------------------
## Rename features (GFF3 type -> Feature key)
[five_prime_UTR]
feature_key = "5'UTR"

[five_prime_utr]
feature_key = "5'UTR"

[three_prime_UTR]
feature_key = "3'UTR"

[three_prime_utr]
feature_key = "3'UTR"

[J_gene_segment]
feature_key = "J_segment"

[V_gene_segment]
feature_key = "V_segment"

[region]
# "region" in GFF3 column 3 corresponds to "source"
# https://https.ncbi.nlm.nih.gov/datasets/docs/reference-docs/file-formats/about-ncbi-gff3/#the-source-region-feature
feature_key = "source"

[transcript]
feature_key = "mRNA"



## --------------------------------------------------------------------------------
## Rename qualifiers (GFF3 attribute --> Qualifier key)

[__ANY__]
## ============== BEGIN ========================
# Originally from GFF3 columns ("source", "score", "phase")
# but translated to qualifier by the GFF parser.

[__ANY__.source]
qualifier_key = "note"
qualifier_value_prefix =  'source:'

[__ANY__.score]
qualifier_key = "score"

[__ANY__.phase]
qualifier_key = "codon_start"  # 0-based in GFF3. Will be transformed to 1-based.
## ============== END ==========================

# --------------------------------------------
# Found in GFF3 attributes
[__ANY__.ID]
qualifier_key = "note"
qualifier_value_prefix =  "ID:"

[__ANY__.Note]
qualifier_key = "note"

[__ANY__.Dbxref]
qualifier_key = "db_xref"

[__ANY__.gene_name]
qualifier_key = "gene"

[__ANY__.geneID]
qualifier_key = "gene"

[__ANY__.description]
qualifier_key = "product"

[__ANY__.eC_number]
qualifier_key = "EC_number"

[__ANY__.ec_number]
qualifier_key = "EC_number"

[__ANY__.locus_tag]
qualifier_key = "locus_tag"
qualifier_value_prefix =  "<dummy>"

[__ANY__._Description]
qualifier_key = "product"


## --------------------------------------------------------------------------------
## Translate a GFF3 type (= column 3 value) into a pair of (Feature, Qualifier)

## ------------- BEGIN ------------------
## https://www.ddbj.nig.ac.jp/news/ja/2007-12-07.html

## In this case, "type" value miRNA in GFF3 is translated to
## ncRNA feature with /ncRNA_class="miRNA" qualifier
[miRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "miRNA"

[piRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "piRNA"

[rasiRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "rasiRNA"

[scRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "scRNA"

[siRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "siRNA"

[snoRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "snoRNA"

[snRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "snRNA"


# http://www.sequenceontology.org/browser/current_svn/term/SO:0001877
[lncRNA]
feature_key = "ncRNA"
qualifier_key = "ncRNA_class"
qualifier_value = "lncRNA"

## ------------- END --------------------




## --------------------------------------------------------------------------------
## Translate a GFF3 attribute (with certain value) into a Feature

## In this case, RNA "type" with biotype="misc_RNA" in GFF is translated to
## "misc_RNA" feature in annotation.
[RNA]
[RNA.biotype]
attribute_value = "misc_RNA"
feature_key = "misc_RNA"
