## Originally prepared by EMBLmyGFF3

[five_prime_UTR]
target = "5'UTR"

[three_prime_UTR]
target = "3'UTR"

# GFF.parse() used in this tool converts this way already: 'transcript' -> 'mRNA'
[transcript]
target = "mRNA"

[region]
# "region" in GFF3 column 3 corresponds to "source"
# https://https.ncbi.nlm.nih.gov/datasets/docs/reference-docs/file-formats/about-ncbi-gff3/#the-source-region-feature
target = "source"
